POST http://127.0.0.1:5000/account/add
Content-Type: application/json

{
    "client_id": 1,
    "service": 2,
    "service_data": {
        "3": 13,
        "4": 14
    }
}

###

PUT http://127.0.0.1:5000/account/edit
Content-Type: application/json

{
    "client_id": 1,
    "service": 2,
    "service_data": {
        "3": 23,
        "4": 24
    }
}

###

DELETE http://127.0.0.1:5000/account/delete
Content-Type: application/json

{
    "client_id": 1,
    "service": 2
}